---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: policies
  namespace: bulwark-gateway
  labels:
    app.kubernetes.io/part-of: bulwark-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siem-stats
  namespace: bulwark-gateway
  labels:
    app.kubernetes.io/part-of: bulwark-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telemetry-data
  namespace: bulwark-gateway
  labels:
    app.kubernetes.io/part-of: bulwark-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-data
  namespace: bulwark-gateway
  labels:
    app.kubernetes.io/part-of: bulwark-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports
  namespace: bulwark-gateway
  labels:
    app.kubernetes.io/part-of: bulwark-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications-data
  namespace: bulwark-gateway
  labels:
    app.kubernetes.io/part-of: bulwark-gateway
    app.kubernetes.io/component: notifications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
